#!/bin/sh
#
# A git commit hook to validate the YAML files when committing and
# will fail the commit if it doesn't parse correctly.
#
# To enable this hook, copy this file to ".git/hooks/pre-commit".

# Redirect output to stderr.
exec 1>&2

# run yamllint on all yaml files in the repo
yamllint --no-warnings --config-data="
---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas:
    level: warning
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  indentation:
    level: warning
  key-duplicates: enable
  key-ordering: disable
  line-length:
    level: warning
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces:
    level: warning
  truthy:
    level: warning
" **/*.yml
