name: Trigger website rebuild

on:
  push:
    branches: [master, prod]

permissions: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.WEBSITE_BUILD_APP_ID }}
          private-key: ${{ secrets.WEBSITE_BUILD_KEY }}
          owner: thunderbird
          repositories: thunderbird-website
          permission-contents: write

      - uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: thunderbird/thunderbird-website
          event-type: ${{ github.ref_name == 'prod' && 'prod' || 'stage' }}
          client-payload: '{"message": "thunderbird-notes ${{ github.ref_name }} push"}'
