name: Trigger website rebuild

on:
  push:
    branches: [master, prod]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: app-token
        with:
          app-id: ${{ secrets.WEBSITE_BUILD_APP_ID }}
          private-key: ${{ secrets.WEBSITE_BUILD_KEY }}
          owner: thunderbird
          repositories: thunderbird-website

      - uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: thunderbird/thunderbird-website
          event-type: ${{ github.ref_name == 'prod' && 'prod' || 'stage' }}
          client-payload: '{"message": "thunderbird-notes ${{ github.ref_name }} push"}'
